### ISSUE TITLE
When selecting page to be for shop cant choose templates- wanted no sidebar template

### ISSUE THREAD

**Issue by kangarooo** [bootscore/bootscore#125]
When selecting page to be for shop cant choose templates- wanted no sidebar template
https://wpexplorer-themes.com/total/docs/woocommerce-shop-page/

**Comment by crftwrk** [comment]
It's not possible to select page-templates for shop because WooCommerce uses `woocommerce.php`. You can quickly change this to a no-sidebar template in two ways:

1. Copy `woocommerce.php` to bootcommerce-child's root folder and go in this file to line `34`. There you will find `<?php get_sidebar(); ?>` Just delete this.

2. The content of `woocommerce.php` is dynamic. If there is no sidebar widget is active, content will take the entire width. You can hide sidebar-widgets with [Widget Context Plugin](https://wordpress.org/plugins/widget-context/) on shop-pages by selecting "Hide Widget on selected" and set to "All Products posts" in widget settings.

Solved?

**Comment by kangarooo** [comment]
But in cart i can choose no sidebar.

**Comment by crftwrk** [comment]
Yes, that's because cart is not a WooCommerce page. It's just a default page with shortcode `[woocommerce_cart]`

**Comment by kangarooo** [comment]
Oh, thx.
