### ISSUE TITLE
Migrating Bootscore to Full Site Editing Gutenberg?

### ISSUE THREAD

**Issue by SamuelMiller** [bootscore/bootscore#142]
Any plans to update Bootscore to WordPress 5.9's Gutenberg block system, using theme.json, HTML templates, etc?

**Comment by crftwrk** [comment]
Hi Samuel,

we will not do this. Because bootScore is a developer project it's much more easier and cleaner to change code in template files than editing the theme in blocks. It will be hard to control design and functionality. That's why bootScore disable Gutenberg blocks in widgets as well. Gutenberg for content, yes. Gutenberg for theme design, no.
