### ISSUE TITLE
content min-height

### ISSUE THREAD

**Issue by neerbappoo** [bootscore/bootscore#143]
Is there any reason why on markup.scss there is a min-height of 600px for the content ID ?
And how to remove that on child theme ?

**Comment by crftwrk** [comment]
Yes, that's because if you have a site with just line of content then the footer will stuck in the middle of the screen.

You can simply override this in your child:

```css
#content {
  min-height: auto;
}
```

A user created a sticky footer plugin: https://github.com/norico/BtScore-Footer-Adjust

This plugin pushes the footer always to the bottom of the browser window even you have just one line of content and have disabled the `min-height`. So, maybe this is what you are looking for.

Does this help?

**Comment by justinkruit** [comment]
An alternative for this, is a height 100% on html and body, and use flex to push the footer down. But that is something we could consider for the theme itself.

**Comment by neerbappoo** [comment]
Thanks for the help !

**Comment by crftwrk** [comment]
I reopened this issue because as @justinkruit mentioned, we can add this to the theme. It's better than the `min-height`. 

https://github.com/bootscore/bootscore/issues/29 @norico do you want to do that?
