### ISSUE TITLE
Child theme php error

### ISSUE THREAD

**Issue by phrizm** [bootscore/bootscore#151]
Hello Basti, thanks a lot for this great theme. 

I have a question regarding child theme, once installed main one and child, i got this strange error: 

Warning: filemtime(): stat failed for /home/mhd-01/*sitename*/htdocs/wp-content/themes/bootscore-child-main/css/main.css in /home/mhd-01/*sitename*/htdocs/wp-content/themes/bootscore-child-main/functions.php on line 11.

I have checked twice documentation available on project website, but got no luck to find an answer. 
Since im new in all that web stuff, i know basic theme structure, functions etc. but never worked with child themes. 

Thanks for your further answer, and keep going with this beautiful dev.

**Comment by crftwrk** [comment]
Transferred this issue to main-theme, because both has nothing to do with child-theme.

https://www.phrizm.com

I tested the site in different browsers and works fine everywhere, even when resizing the window. You use WP Fastest Cache plugin. So, it's possible that you see something different when you are logged in as an admin. Disable plugin for testing and make a short video screenshot that shows the error.

https://www.northwestalps.com

This site shows a fatal error in `wp-blog-header.php` now. There is something completely wrong on your site. If you haven't touched the theme or child-theme's code, then it's a plugin.

- If you have still access to the backend, go to plugin page and disable all plugins. Then enable step by step each plugin again until you have found it.
- If backend is crashed as well, log in via ftp and rename all plugin folders to disable them. Then rename them step by step to origin name.

**Comment by phrizm** [comment]
Basti, 
have requested a purge by my hosting. 
They deleted all existing files. I think it was something to deal with previously installed theme, that actually create some hidden Type of files as hosting said.

Im really sorry for your time spent with me, but you were right about hosting issue.

Ok! Since things works im gonna destroy it by my own hands now xD.

Thanks a lot for your kind support.

**Comment by crftwrk** [comment]
You‘re welcome, we‘re here to help😉
