### ISSUE TITLE
Mega menu

### ISSUE THREAD

**Issue by lennertfabriek** [bootscore/bootscore#162]
Hi Basti,

Is it possible to create a mega menu with the existing navwalker?

**Comment by lennertfabriek** [comment]
For now I created a custom div with display none and get visible when hovering. (website.oneshot.nl). Is there a better solution or is this okay? Btw it is only working on other pages than home. I don't know why (yet).

**Comment by crftwrk** [comment]
Hi Lennart,

not so easy because nav-walker follows straight Bootstrap way and this means:

- Only 2 levels depth.
- Open dropdown on click and not on hover.

But it's possible with some custom coding. A good source with some examples and snippets is https://bootstrap-menu.com. 

There are some discussions on nav-walker issues about this too https://github.com/AlexWebLab/bootstrap-5-wordpress-navbar-walker/issues/19, https://github.com/AlexWebLab/bootstrap-5-wordpress-navbar-walker/issues/26.

The nav-walker is a pluggable function in `functions.php`. So you can override this file safely in your child.

Your solution is ok, but there problems on mobile. Maybe adjust them via media-queries? What's about to hard-code it without the nav-walker?

Does this help?

**Comment by lennertfabriek** [comment]
Hi! 

I get it. Hard coded menu is an idea but I like the current one. Then I prefer my solution for now, this one is also customizable at any wishes. For mobile I just want to use another menu without drop down. 

Thank you Basti.

**Comment by crftwrk** [comment]
You‘re welcome👍
