### ISSUE TITLE
Release doesn't contain CSS?

### ISSUE THREAD

**Issue by steliosmac** [bootscore/bootscore#177]
I may be missing something, but I just downloaded Bootscore to use for a project, it seems like I need to seperately download and upload the bootstrap CSS, it's not included in the downloaded files.

**Comment by crftwrk** [comment]
Correct, CSS is not included because the CSS file is automatically created by scssphp on first page load or when changing something in SCSS files. Just install theme and refresh frontend.

Does this help?

**Comment by steliosmac** [comment]
Doesn't seem to be doing that for whatever reason, at least for my site (Fresh WordPress install on Runcloud - NGINX/Apache Hybrid)

**Comment by crftwrk** [comment]
Try to force scss compile when environment is development. Add this to `wp-config.php`:

```php
/* Dev mode to force recompile scss and add source map */
define('WP_ENVIRONMENT_TYPE', 'development');
```

**Comment by sagehenstudio** [comment]
Can I just mention the _elephant in the room_? This theme doesn't use semantic versioning, so what I thought would be a fairly painless upgrade from 5.1 to 5.2 ended up requiring quite a bit of time moving files and renaming them.

Hints I hope help some people who have also been using BootScore for a while: 

SCSS (`_bscore_custom.scss`, `_bscore_variables.scss` and `main.scss`) are moved out of the child theme "css" folder into a new standalone "scss" folder in the theme folder, and what was previously called `/css/lib/bootstrap.min.css` is now `/css/main.css` - requiring some changes to the functions.php file. If you don't see your css compiling, it could be because your functions.php file is still looking for a file that is no longer used.

**Comment by justinkruit** [comment]
The versions are equal to Bootstrap, we try to honor those.  The changes that need to be made are always mentioned in the blog post of the version: https://bootscore.me/blog/bootstrap/bootscore-5-2-0-0/

**Comment by crftwrk** [comment]
@sagehenstudio moving from `bootstrap.min.css` to `main.css` was part of a larger roadmap to improve theme since we have Bootstrap source and scssphp in theme. Why we allow us to do drastic changes and is described here https://bootscore.me/documentation/theme/updates/

However 5.2.0.0 was the final release with changes there, future updates should be more "painless". Our goal is of course to provide smooth updates as well. But if a breaking change happens, we do a blog post with exactly instructions how to update and you get a newsletter in your mailbox if you are subscribed to the newsletter. If you haven't subscribed yet, you can do it here to be up-to-date what's going on or follow us at https://twitter.com/_bootscore

**Comment by sagehenstudio** [comment]
I just assumed most the world was using semantic versioning and clicked to download 5.2.2. Not everyone is tied up in the nuances of your unique versioning and Bootstrap your blog and whatnot. I just like the theme. Thank you. 

This is a quite breaking update. You can call it what you want, but I'll call it 6.0. 🤪
