### ISSUE TITLE
Bootstrap rtl

### ISSUE THREAD

**Issue by vahidalvandi** [bootscore/bootscore#181]
in your sample we cant compile bootsrap 5 with rtl option and have slow compile , i think if you include bootstrap.min.css in header and add same override method like change color and use same helpers like reponsive use this scss stracture.

please see https://github.com/vahidalvandi/starter-mix-bootstrap5/tree/main/src/sass

import necessary libs without origin   @import "~bootstrap/bootstrap
```
@import "~bootstrap/scss/functions";
@import "_variables";
@import "~bootstrap/scss/_variables";
@import "~bootstrap/scss/mixins/breakpoints";
@import "~bootstrap/scss/mixins/buttons";
@import "~bootstrap/scss/mixins/transition";
@import "~bootstrap/scss/mixins/gradients";
@import "~bootstrap/scss/mixins/box-shadow";


$theme-colors: (
        "primary": $primary,
        "secondary": $secondary,
        "success": $success,
        "info": $info,
        "warning": $warning,
        "danger": $danger,
        "light": $light,
        "dark": $dark
);

@each $color, $value in $theme-colors {

  .btn-#{$color} {
    @include button-variant($value, darken($value, 7.5%), lighten($value, 90%), lighten($value, 5%), lighten($value, 10%), lighten($value, 70%));
  }

  .text-#{$color} {
    color: $value !important;
  }

  .bg-#{$color} {
    background-color: $value !important;
  }

  .table-#{$color} {
    background-color: $value !important;
  }

  .link-#{$color} {
    color: $value !important;
  }

}

@import "./style.scss";

```

**Comment by crftwrk** [comment]
Ok, I learned now that adding `dir="rtl"` to the `<html>` is not enough to create rtl pages. There must be a compiled Bootstrap rtl as well. Correct?

I did not find any rtl source or good documentation about this in the web. Please explain how the rtl build process works.

Linking the `bootstrap.min.css` in the header is not an option, because we use scssphp to compile and we will not change this. 

However, the rtl css is necessary for some components like:

- Accordion
- Input groups
- Selects
- Pagination
- Dropdowns
- Modal
- etc

It seems to me not that much to create an rtl scss file to fix them. We can add this to main-theme source and `//@import "bscore_rtl";` in child. By removing the `//` comment the site is rtl. What do you think?

**Comment by justinkruit** [comment]
Bootstrap uses an external service to create the RTL, this is not integrable with scssphp.

**Comment by vahidalvandi** [comment]
> Ok, I learned now that adding `dir="rtl"` to the `<html>` is not enough to create rtl pages. There must be a compiled Bootstrap rtl as well. Correct?
> 
> I did not find any rtl source or good documentation about this in the web. Please explain how the rtl build process works.
> 
> Linking the `bootstrap.min.css` in the header is not an option, because we use scssphp to compile and we will not change this.
> 
> However, the rtl css is necessary for some components like:
> 
> * Accordion
> * Input groups
> * Selects
> * Pagination
> * Dropdowns
> * Modal
> * etc
> 
> It seems to me not that much to create an rtl scss file to fix them. We can add this to main-theme source and `//@import "bscore_rtl";` in child. By removing the `//` comment the site is rtl. What do you think?

no same components like paginate not work and need use bootsrap.rtl.css aslo need dir="rtl"

**Comment by crftwrk** [comment]
You can now disable scssphp and use gulp or anything else to compile rtl CSS https://github.com/bootscore/bootscore/pull/375.
