### ISSUE TITLE
Repo settings

### ISSUE THREAD

**Issue by justinkruit** [bootscore/bootscore#187]
I've enabled protected settings for the main branch. Non-admins can't push commits the main branch anymore, they're required to send a pull request.

Do we want to enable Discussions and/or Sponsorships @crftwrk?

**Comment by crftwrk** [comment]
Good, thank you!

Yes, I'm fine to enable Discussions and Sponsorship. But I'm not sure if we can find someone who wants to sponsor this tiny project, but let's try.

**Comment by crftwrk** [comment]
Been thinking about this for a while. 

Setting up the sponsor page is a bit more than I thought and we should do this carefully to get the chance to catch real sponsors. We also have to think about how the money should then be shared.

The discussions are a community and we need users to get this alive.

Later this year, I would like to remove all free products from the shop, add new paid child-themes there and provide direct download links for the free products instead. Because there are too much orders every day and database gets crowded.

This seems to be a good point for me to open the sponsors and discussions and inform users by blog and newsletter. Is this an idea?

**Comment by justinkruit** [comment]
Yeah, I agree. I also paused setting up the sponsor page simply because it had too many inputs of which I didn't know what to do with them.

Removing the free products could be a good plan, especially if you're getting sick of too many free orders.

**Comment by hsankala** [comment]
Yeah I second this thought it cool at first having the theme and child theme as downloadable items on the account on your website.  But would make sense to have direct links to the packages.  

I've seen some other developers just point people to their github and ask them to download the latest release package.

**Comment by justinkruit** [comment]
Completely fine by me, otherwise we may make too many changes all at once. Let's indeed focus on the discussions and direct downloads.

**Comment by hsankala** [comment]
I guess for sponsorship, sponsors want something for their money.  So like you say you _'need to get give a clear picture of the benefit to the sponsor'_

Promotion around core benefits bootscore

- Easy of use
- Solid 
- Bootstrap latest version
- Great plugins
- Support
- WordPress
- Fast
- Developer and Scaling safe
- etc etc

I guess you'll looking for companies who then will use the product in the long term for their web developments and want to sponsor the maintenance and evolution of the product.

Suppose you got to take off the developer hat and put on the marketer and salesman hat.  Build the brand and sell the concept of premium developer-centric theme, that is going to save a massive amount of time at project intiation and is going to be a solid foundation and platform to build off like other:

- Astra
- Genesis
- Elementor - Hello Theme  (not so much this because it's tied to a pagebuilder product)
- Divi
- StoreFront
- OceanWP

**Comment by crftwrk** [comment]
Here we go:

- https://bootscore.me/#download
- https://bootscore.me/blog/news/final-move-to-github/

**Comment by justinkruit** [comment]
I visited the download page just now, and maybe it's a nice idea to add a small GitHub button after each theme and plugin that's on here? Can't remember the layout on pc that quickly, but on mobile having a small button right from the download button would be a nice addition.

**Comment by crftwrk** [comment]
https://github.com/sponsors/bootscore
