### ISSUE TITLE
Problem with the end of page (footer)

### ISSUE THREAD

**Issue by exlexv** [bootscore/bootscore#191]
Hello! Just have updated theme to 5.2.0.0. Made all the necessary changes in child (5.1.3.2). And now footer and a section above it suddenly show up in the beginning of the page. 

Did some tests, made new installation of parent and child to see what went wrong. So6 everything works fine till the moment  I add my template and template-parts folders into child root directory.  e.g. my template for home page looks like this:
<img width="628" alt="Снимок экрана 2022-07-24 в 18 16 15" src="https://user-images.githubusercontent.com/108526222/180653826-ce60249e-c2f6-4f06-b693-e30001f6b19d.png">

Nothing special, but the page is messed up. On 5.1.3.2 works fine, and on 5.2.0.0 works fine when "bald" until I add template-part and templates folders. Site is at https://yass.center/main . Could you help, please?

P.S. Same chaos happens even after I make brand new install of 5.2.0.0 parent and child and add template folders (even without my custom css).

P.S. Something strange has happened. Suddenly the problem got fixed. But offcanvas stoped working!!

**Comment by crftwrk** [comment]
Hello,

at first glance your footer looks good? But you still have not enqueued `main.css` in your child? Please check here https://bootscore.me/blog/bootstrap/bootscore-5-2-0-0/ again to make sure to have all needed steps in your child done. 

Your Offcanvas stops working because you are use Bootstrap 5.2.0 JavaScript and 5.1.3 CSS. I suggest to install fresh bootcommerce-child https://github.com/bootscore/bootcommerce-child/releases/download/v.5.2.0.0/bootcommerce-child-main.zip and do changes by copying files from your old child to the new one.

We did not change anything relevant in `footer.php`. A first look to the code in your image seems that there are a lot missing close tags, that's why your footer crashed. Try this: 

```php
<?php
/*
Template name: Home
*/
get_header();?>
<main id="main-container" role="main" class="container-fluid px-O">

  <article id="post-<?php the ID(); ?>" <?php post class(); ?>><!-- missing > -->
    <div class="entry-content">
      <?php
        get template part('template-parts/home/home' , 'hero');
        get_template_part('template-parts/home/home' , 'about');
        get template part('template-parts/home/home' , 'quotes');
        get_template_part('template-parts/home/home' , 'recentblog');
      ?>
    </div><!-- missing close tag .entry-content -->
  </article>

</main>
<?php get_footer(); // Do not close this, will be closed in footer.php
```

Does this help?

Ps. Please post in further issues code snippets instead images. It's better ;-)

**Comment by exlexv** [comment]
Hello, did like you said, edited template page, even deleted my own footer (left the main one in parent theme, it still messes with layout. Single.php and category.php work fine.

I understood about Offcanvas. Now just can't make the template pages work correctly. In 5.1.2 everything works like magic)

**Comment by crftwrk** [comment]
Please send 2 links to check this. One where the footer is broken and another one where the footer is fine.

There is something in your page template wrong. If it's not the `home.php` by itself, then it's somewhere inside the `template-parts`. I suggest to comment each line and check where the error happens. It must be one (or more) missing close tags.

However, may I ask you why so complicated using `home.php`? It seems that the `template-parts` just contain plain HTML, right? 

If so, just set up a new page and choose `page-blank` template. Then copy HTML to a Gutenberg HTML block. Go in backend to Settings > Reading, set new page to frontpage and delete `home.php`.

Your `margin-top` on `#masthead` works fine?

**Comment by exlexv** [comment]
Thank for the response. As I've written earlier - Update:

   1.  Fixed problems with footer. Indeed, it was my spaghetti code%).
   2.  For top spare space on a page I created class with margin-top and added it to -header-. Don't know why it didn't work on #masthead.
   3.  Why not to choose page-blank? Idk, just used to doing like that, editing files in Atom)

Thanx again!

**Comment by crftwrk** [comment]
Cool 👍

Height doesn't work well in masthead. Had the same problem as well. I solved it ba adding an extra `<div class="spacer">` to `header.php` and added some margin:

```html
...

  </div><!-- .fixed-top .bg-light -->

</header><!-- #masthead -->

<div class="spacer"></div>

```

```css
.spacer {
  margin-top: 100px;
}
```

Everything solved?

**Comment by exlexv** [comment]
Well yeah, that is another way to make some space. 

Everything is fine now. Thanks so much& However) I've wanted to ask on another issue I've had with headroom.js. I use it on #nav-boot.

First time when I used it, main offcanvas menu on smaller screens didn't show up (other menus, cart, user were ok). So I had to duplicate Offcanvas Navbar and paste it under ' </div>' so when I call for Offcanvas Navbar on a toggler — the duplicated one shows up. "Bootstrap 5 Nav Walker Main Menu" on the duplicated Offcanvas is set to d-lg-none. Maybe there is a more adequate solution to it?)

**Comment by crftwrk** [comment]
Navbar Offcanvas is different from default Offcanvas because it's inside the `.navbar` while cart and user are outside. If you doing some effects on the navbar it will affect the navbar offcanvas as well. If you want to use effects, there is no other way by placing it outside the `.navbar` and using `d-lg-*` class. All good.

**Comment by exlexv** [comment]
Thank you!

**Comment by crftwrk** [comment]
You're welcome 👍
