### ISSUE TITLE
Problem with offcanvas

### ISSUE THREAD

**Issue by svedb** [bootscore/bootscore#200]
data-bs-toggle="offcanvas" data-bs-target="#offcanvas-cart" attached to add to cart button for products that require select options or read more, thus toggling offcanvas cart when clicking to Select Options or Read More.

**Comment by crftwrk** [comment]
Offcanvas cart opens when you add something to the cart. This is what a cart exactly should do and works fine with:

- Simple products
- Variable products
- Grouped Products

Works not with:

- Affiliate products

Please describe issue more detailed and share a link to your project to check your issue. 

Thanks!

**Comment by svedb** [comment]
Thank you for responding so promptly.  My project right now is on LocalWP.  I don't know if it has done this spontaneously. I recall early on "Read More" would trigger the offcanvas cart. But again with a plugin WPC Grouped, Select Options triggers the offcanvas cart. 

`<a href="http://bootcommerce.local/?product=test-product" data-quantity="1" class="add_to_cart_button product_type_woosg single_add_to_cart_button btn btn-primary d-block " data-product_id="41" data-product_sku="" aria-label="Read more about “Test Product”" rel="nofollow" data-bs-toggle="offcanvas" data-bs-target="#offcanvas-cart"> Select Options</a>`

It is not possible to use third party plugin in this case, because I was certain it was working. Do you know of any workaround?

**Comment by crftwrk** [comment]
Unfortunately it’s absolutely impossible to check something on your local machine. That‘s why specific problems must have a link with live example as described here https://bootscore.me/documentation/support-contribute/#What_we_do

Please transfer your project to a public server and share links to the pages where your issue appears and describe each. So, we can check and help.

Thank you!

**Comment by justinkruit** [comment]
If you don't want the offcanvas to happen on that button, you should add the `.product_type_woosg` class to the `:not` checks on this line: https://github.com/bootscore/bootscore/blob/c61c68cbbf0502b1bf2f76ea95e0ac22be01080b/woocommerce/js/woocommerce.js#L3

@crftwrk instead of checking all the `:not`, can't we just check if it's a simple product?

**Comment by svedb** [comment]
> Excuse the comment if it has any weird formatting, doing this support from my phone.

@justinkruit Thank you, you have resolved this issue.

**Comment by crftwrk** [comment]
> instead of checking all the :not, can't we just check if it's a simple product?

@justinkruit yes, better. Do you have any idea to solve this in product pages for grouped and variable products? Because they use the `single_add_to_cart_button` as well.

If we do something like `$('.product-type-simple .single_add_to_cart_button').attr('data-bs-toggle', 'offcanvas').attr('data-bs-target', '#offcanvas-cart');` it will work in product loop but not in product pages.

Any idea?

**Comment by justinkruit** [comment]
Just did some testing, and I ended up with the same jQuery function, although for me it works on both the category page and the product page. Are you sure it wasn't working @crftwrk ?

**Comment by crftwrk** [comment]
Did you tested it with grouped and variable products?

**Comment by justinkruit** [comment]
Ah, I see what you mean now. Fixed it with this:
`$('body.archive .product-type-simple .single_add_to_cart_button, body.single-product .single_add_to_cart_button').attr('data-bs-toggle', 'offcanvas').attr('data-bs-target', '#offcanvas-cart');`

**Comment by crftwrk** [comment]
PR?
