### ISSUE TITLE
Problem with bootScore template.

### ISSUE THREAD

**Issue by siajo** [bootscore/bootscore#265]
Hi. I have a problem with the bootScore template and the plugin from wp-desk InPost Paczkomaty. Everything works on the default theme. The window with the choice of parcel machines does not appear on the bootScore template.
Something's blocking him. https://watch.screencastify.com/v/dkIrV0rkoCTA5AVYkPVH

No errors will appear in the console. I wrote to WP_desk. They did the trick: our plugin works with the default Storefront. This means that the bootScore theme is blocking our InPost and they will be able to address this problem. Please help

**Comment by crftwrk** [comment]
It is impossible to check this via a video. Please share a link to your project.

**Comment by siajo** [comment]
Hi. I send link to project: https://bimberek.pl/ 
You need to add the product to the basket and select the InPost parcel locker

**Comment by crftwrk** [comment]
It opens, but needs a very long time.

<img src="https://user-images.githubusercontent.com/51531217/192590680-69cdbf8a-beb6-4fe4-80d5-91bebb5df364.png" width="400">


There is something what needs long to load and there is a loading spinner on the mouse. What it is I cannot say. But what I can say that you use bootScore 4.0.4, which is EOL since 2020. So, there must be a lot of outdated WooCommerce template files in your theme.

You said it works fine with other themes? I suggest to use latest 5.2.1.1 version and transfer your modifications to bootcommerce-child theme.

- https://github.com/bootscore/bootscore/releases/download/v5.2.1.1/bootscore-main.zip
- https://github.com/bootscore/bootcommerce-child/releases/download/v.5.2.0.0/bootcommerce-child-main.zip

Let me know if that works.

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.

**Comment by crftwrk** [comment]
Hi,

it is impossible to check this with a single sentence. You wrote that parcel works fine with other themes. So, if you want to check this issue seriously, do this:

- Create 2 fresh WordPress installations in English
- Only WooCommerce and parcel plugin
- Only 1 product
- One site with a default theme, the other with latest bootscommerce-child
- Share links

Then we can investigate further.

Thank you
