### ISSUE TITLE
Search bar overlapping nav items

### ISSUE THREAD

**Issue by pandanas69** [bootscore/bootscore#28]
Hi,

At about tablet width the search widget moves over the nav items text. Any fix for this please?

Thanks,

Andrew

**Comment by crftwrk** [comment]
Hi Andrew,

please check here the header documentation https://bootscore.me/documentation/header-php/ too.

Header uses `fixed-top` as described in https://github.com/bootscore/bootscore/issues/26. Search uses `collapse` component. In combination with header class the search cover the content. If you want to push content down instead of overlapping when opening the search-form, just remove `fixed-top` class.

You have this custom CSS on your site:

```
@media (min-width: 768px)
.searchform {
    max-width: 50% !important;
    float: right;
}
```

This will crash your search-form.

**Comment by pandanas69** [comment]
Hi,
Thanks for your help. I added that as the search form takes up full width on desktop. How do you mean, will crash?

**Comment by pandanas69** [comment]
I see. Cool, thanks. Keep up the good work! Much appreciated.

Andrew

**Comment by pandanas69** [comment]
Sorry to bug you, I'm sure your busy but one more thing please before I close these 'issues' for the life of me I can't get the logo to just the right size before the nav spills over under it on mobile. I've tried resizing the .svg and adding css to no avail. I guess it's probably not a good idea to have small lettering in a logo but still..
I've tried padding:0;; margin:0; position:relative;  any thoughts?
Thanks so much!
