### ISSUE TITLE
Update Checker

### ISSUE THREAD

**Issue by crftwrk** [bootscore/bootscore#30]
## Update Checker

With Bootstrap 5.2.0 we can include the [Update Checker](https://github.com/YahnisElsts/plugin-update-checker). This script is already installed  in bS Swiper and bS Grid plugin and works fine. Bootstrap 5.2.0 removes `navbar-light` variables and I'm not sure if there is a Sass error if this variables are used in child. That's why waiting until 5.2.0.

### Motivation

Providing single-click updates in the backend.

> From the users' perspective, it works just like with plugins and themes hosted on WordPress.org. The update checker uses the default upgrade UI that is familiar to most WordPress users.

### Risks

By including the script, we‘re leaving the comfort and enter the danger zone, because we‘re not able to do breaking changes which will affect existing child-theme installations anymore. Classes, filenames, folders etc. cannot be changed after including the script. I‘m not 100% fine with naming and folder organisation, but it works well and we can address breaking changes to v6.

### To-do

- [ ] Check if there are potential issues with classes, folders etc. If so, changes must be made now and written down in an update-guide.
- [ ] Install script
- [ ] Write docs how to disable updates if user want to edit parent-theme

@justinkruit @Axos11 what do you think?

**Comment by justinkruit** [comment]
I'm sorry, kept the email of this issue open to respond, but kept forgetting.

I'm personally not a big fan of automatic updates for things of which the code is supposed to be changed, even with child themes. For every small change, you'll need to be backward compatible, and that will be a lot of work to maintain instead of just making improvements and making it up to the other devs if they want to implement them. If a user uses bootScore, I'm pretty sure they already have some code knowledge to kinda take it up to themselves.

**Comment by crftwrk** [comment]
Agree.
