### ISSUE TITLE
Product display issue on single and admin

### ISSUE THREAD

**Issue by bnbrndn** [bootscore/bootscore#324]
Having an issue with my local and staging enviroment where the product single page isn't fully showing, also having a similar issue on the admin for single products as shown below.

I'm using a child theme, with no changes to those templates as of yet.

![Screenshot 2022-12-06 at 16 03 51](https://user-images.githubusercontent.com/22602995/205962068-30a96356-934c-4604-8ad2-5d7fa2978afa.png)

![Screenshot 2022-12-06 at 16 02 50](https://user-images.githubusercontent.com/22602995/205961836-165ec2b6-e65e-4673-8177-0278f489787b.png)

**Comment by crftwrk** [comment]
Hi,

this has for sure nothing to do with theme, because bootScore doesn't do anything in the admin backend. It seems more than a WP/WC misconfiguration or an issue with your local server. Which local machine do you use?

However it's not possible to check something on your local machine. If you want that we have a look to it, please transfer your project server and share a link to it.

**Comment by bnbrndn** [comment]
Hi,

I use laravel valet locally, however as mentioned I'm having the same issue on my staging enviroment. I'm also using Bedrock, not sure if this is related.

link to my staging enviroment is: https://staging.thedrivershq.co.uk

Thanks,

**Comment by crftwrk** [comment]
https://staging.thedrivershq.co.uk/product/vp-the-essentials-box-pop-your-vp-cherry/ this?

There are at least 4 errors on each page coming from the vmm search plugin.

<img width="395" alt="screenshot" src="https://user-images.githubusercontent.com/51531217/206037677-6405bff7-3559-4efa-a330-db2947cfdf15.png">

Did you tried to disable **all** plugins (except WooCommerce) and using a fresh bootcommerce-child without any modifications?

**Comment by crftwrk** [comment]
Haven't heard anything here for a while, will close this issue now.
