### ISSUE TITLE
bootscore_ie_alert() gets cached

### ISSUE THREAD

**Issue by Axos11** [bootscore/bootscore#37]
I just had the issue on a client site that the function bootscore_ie_alert() output gets actually pagecached if the first user to open the site after a cache clear is a IE User. Also, the function is not triggered if the page is already cached. As caching is very important for the sites speed i would suggest to move that check to an js function or an ajax call to prevent it beeing cached.

**Comment by crftwrk** [comment]
I'm more a friend of removing this function. Bootstrap were the first who dropped the support for IE but many others like WooCommerce followed quickly. Created this function when doing the step from v4 to v5 to make clear that there is no support for this browser anymore. But now we have 2021 and there are [polyfills](https://github.com/coliff/bootstrap-ie11) to make Bootstrap 5 compatible with IE 11.

However, many users like this function. So, not sure to keep it or remove it. Addressed this point already to v6. A js version will give us more control to remove it later again instead using a hook and function. On the other hand I try to remove js wherever it's possible. So, no idea what's the best at this point.

**Comment by Axos11** [comment]
I think the function kind of "helps" pushing people to modern browsers. And I agree that eliminating js where possible is a good idea (maybe could add it as a plugin?)

We could insert it the same way it is right now or as an Overlay. However, it has to be inserted into the page with js in my opinion because I have no idea how to avoid the page cache otherwise.

**Comment by justinkruit** [comment]
I think the js isn't even that heavy, just an user agent check and go from there. You can even keep the alert in html and only remove d-none class when the user agent matches.

**Comment by Axos11** [comment]
I would just try to put the alert as far as possible to the bottom to prevent Google from catching it somehow as a important component when it's crawling. Could work as a toast then.

**Comment by crftwrk** [comment]
In an earlier version was an pure HTML and CSS solution using `<!--[if IE]>...<![endif]-->` and `@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {...}`. But I was afraid that Google could crawl that. So, decided to use a PHP function instead.

Toasts are very cool, but is IE able to show them? https://www.browserling.com/browse/win/7/ie/11/https%3A%2F%2Fgetbootstrap.com%2Fdocs%2F5.1%2Fcomponents%2Ftoasts%2F

Have no real IE to test here.

**Comment by Axos11** [comment]
It sadly doesn't completely. It seems that with bootstrap 5.0.3 it worked but 5.1 kinda broke IE support completely. So the pages start to look really ugly if opened with IE.

Because of that i would prefer a fullscreen overlay (like in this example: https://www.pinterest.com/pin/664069907535455886/) to not show off a broken page.

**Comment by crftwrk** [comment]
Agree

**Comment by crftwrk** [comment]
As mentioned in PR https://github.com/bootscore/bootscore/pull/52, we cannot roughly delete IE alert function without crashing users child-themes. Because if we remove function and users have still `<?php bootscore_ie_alert(); ?>` hook in their header.php they will see the "white site of death".

Would suggest this steps:

Bootstrap 5.2 comes closer https://github.com/twbs/bootstrap/projects. Think they release in 1-2 weeks. By this release users get informed that they have to change something in their theme anyway.

### 5.2.0.0 

- We delete `<?php bootscore_ie_alert(); ?>` now, inform in blog post and newsletter that users should remove the hook in header.php. So, temporarily no IE Alert.

### 5.2.X.X

- Because users have removed this we can delete now IE function in template-tags.php safely
- Adding the js version.

In PR is this:

`'<h1>' + /*esc_html__('Internet Explorer detected', 'bootscore')*/'Internet Explorer detected' + '</h1>' +`

The `esc_html__('Internet Explorer detected', 'bootscore')` is the php translation string. Does that work this way?

Do you agree?

**Comment by Axos11** [comment]
Wouldn't it be a possibility to just remove the code in "bootscore_ie_alert()" and make it an empty function? Then nothing actually breaks and we can inform everyone, that that line is deprecated and should be removed in Child themes. in Version 5.3 we remove the function completely. 

Because it is actually non breaking we could add the .js asap. 

I left the translation in the code but commented it out. I thought you might have a working wordpress .js translation solution already :)

**Comment by crftwrk** [comment]
Yes, that sounds good.

- remove `<?php bootscore_ie_alert(); ?>` in header.php and inform user
- empty the function in template-tags.php
- add js alert
- remove empty function later

Is it an option for you to place js in function with `<script>` tag? In this case we can do what we want.

> I left the translation in the code but commented it out. I thought you might have a working wordpress .js translation solution already :)

I have no idea how to translate js. The alert is always in english i guess.

**Comment by justinkruit** [comment]
Translating things in the js files is done with [wp_localize_script](https://developer.wordpress.org/reference/functions/wp_localize_script/). You load the string with that, and then recall them in tje js file.
