### ISSUE TITLE
[Feature Request] Add BS5 Navwalker support for WP NAV Widgets

### ISSUE THREAD

**Issue by seanvandermolen** [bootscore/bootscore#471]
### Describe the feature that you'd like

For consistency and proper classes NAV widgets should use the BS-5 Navwalker by default.

The function is simple enough:

```
add_filter('widget_nav_menu_args', 'my_args'); //for menus in widgets
function my_args($args) { //$args is only argument needed to add custom walker
   return array_merge( $args, array(
        'walker' => new bootstrap_5_wp_nav_menu_walker(),
   ) );
}
```

The Navwalker would need to be updated to remove 'nav-link' discovered in  LI  elements.

Add after line 58 in class-bootstrap-5-navwalker.php
$class_names = str_replace('nav-link ', '', $class_names);

### Why is this feature needed? What problem does it solve?

Any NAV menu will require BS classes which the BS-5-Navwalker solves for the most part.

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
Thank you for this feature request. I've been thinking about this for a while and generally it's a good idea. But there's a reason why we shouldn't do that, let me explain.

Theme disabled Gutenberg widgets and enabled classic widgets by default. In order to keep up with the times, we have now reactivated Gutenberg in widgets https://github.com/bootscore/bootscore/pull/660 and we will add Bootstrap support for them step-by-step.

By enabling GB in widgets, existing nav-widgets move into legacy mode and support for them in WordPress will end. There is currently no GB nav-widget available, but if WP adds a new nav-widget block that will not be supported by the nav-walker. If WP adds a new nav-widget block, we can do nav support for them by adding a filter.
