### ISSUE TITLE
[BUG] PHP errors starting with 5.3.0

### ISSUE THREAD

**Issue by IceflowRE** [bootscore/bootscore#502]
### Describe the bug

```
PHP Notice:  Function wp_enqueue_script was called <strong>incorrectly</strong>. Scripts and styles should not be registered or enqueued until the <code>wp_enqueue_scripts</code>, <code>admin_enqueue_scripts</code>, or <code>login_enqueue_scripts</code> hooks. This notice was triggered by the <code>wc-cart-fragments</code> handle. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in /var/www/html/wp-includes/functions.php on line 5865
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5865) in /var/www/html/wp-admin/includes/misc.php on line 1431
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5865) in /var/www/html/wp-includes/functions.php on line 6896
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5865) in /var/www/html/wp-admin/admin-header.php on line 9
```

5.2.3.4 is not affected.

### Steps to reproduce

Just replace 5.2.3.4 with 5.3.0.

### Screenshots and Additional Info

WooCommerce 7.7.2.
Wordpress 6.2.2

**Comment by crftwrk** [comment]
Do you have `WP_DEBUG` set to `true`? If so, I think you can ignore it, let me explain. 

Version 5.3 ships updates for the upcoming WooCommerce 7.8 (coming next Tuesday) as well. In 7.8 the `wc-cart-fragments` is disabled by default, but bootScore needs this script for the mini-cart in the navbar. See https://developer.woocommerce.com/2023/05/24/woocommerce-7-8-beta-1-released/.

We testet 7.8 updates with some current 7.7 installations and discovered no issues. That's why we decided to ship WooCommerce 7.8 updates in advance with the 5.3 release.

The error should be come by this line in `wc-functions.php`. This is a new file in 5.3:

https://github.com/bootscore/bootscore/blob/fde7023b3a8f3c2889a87618f1b10e51eef06fb1/woocommerce/wc-functions.php#L12

Simply comment or delete line and the error should be solved. But do not forget to enable snippet again on next WooCommerce 7.8 update, otherwise cart in navbar will not work.

**Comment by IceflowRE** [comment]
> Do you have WP_DEBUG set to true? 

Yes. 
Ignoring is quite difficult, as the whole website stops operating.

Will try the fixes! Thanks.

**Comment by crftwrk** [comment]
Got it. Move this line in my previous comment from line `12` to `51` and let me know if that works.

**Comment by IceflowRE** [comment]
Yes, error message is gone then.
