### ISSUE TITLE
Safari scroll fix causes weird behaviour

### ISSUE THREAD

**Issue by Axos11** [bootscore/bootscore#51]
this few lines of code let the browser scroll up to the top on every pageload (if I open a product page from a category page and then hit the back button (category page > product page > category page) then the page is loaded with the correct position and the .js lines let the position jump up and then down again. It's also possible to replicate the issue with just using F5 on a scrolled category page in chrome.

`if (window.location.hash) scroll(0, 0);
  setTimeout(function () {
    scroll(0, 0);
  }, 1);`

As i don't really understand the issue the lines should fix I'm not sure how to fix them (I mean without removing the lines totally :))

**Comment by crftwrk** [comment]
You mean the smooth-scroll script? Created this for one-pagers https://bootscore.me/theme/scrollspy-onepager/#four

Safari is a weird browser and many things are working there not or not as good like in all other Browsers. This script is only there, because Safari is the only modern browser that doesn't yet support `scroll-behavior` https://caniuse.com/?search=scroll-behavior. Hope we can remove this script soon.

**Comment by crftwrk** [comment]
As mentioned in PR https://github.com/bootscore/bootscore/pull/52, this does not work correctly on my devices and it seems too complicated for me. I'm tired of this script too and would suggest this:

- We remove script and use the default `scroll-behavior: smooth;`
- Describe the snippet in docs, so users can add it to their child **or**
- we make a plugin of it **or**
- we do address script and css (`scroll-behavior: auto;`) only to Mac Safari and all iOS devices and place it at the bottom of theme.js. 

I suggest to do this in 5.2.1 as well.

**Comment by crftwrk** [comment]
Script can be removed by iOS 15.4 (expected March 2022) https://caniuse.com/?search=scroll-behavior
