### ISSUE TITLE
Cross Sell Products

### ISSUE THREAD

**Issue by gurpreetbhachu** [bootscore/bootscore#542]
Hi,

Working on a practice project (eCommerce) on Version: 5.3.0

I have a few products under Cross Sell products for a product(Ex: item1).
So, the cross sell items are not displaying on the cart page after adding item1.

Am I missing something? or any settings?
Any suggestions?

Regards,
Gurpreet

**Comment by crftwrk** [comment]
Hi Gurpeet,

you are right. Cross selling in cart is disabled by a function:

https://github.com/bootscore/bootscore/blob/3351cbe1ad9201d518b8432e283d02e54e9747a8/woocommerce/wc-functions.php#L110-L111

We are refactoring the entire WooCommerce part https://github.com/bootscore/bootscore/issues/333 since a while and the cross selling loop in cart do not fit yet. That's why cross selling is disabled for now, but it's planned to enable in v5.4.

If this is urgent for you, you can create a pull request and wrap the line in a pluggable function `if (!function_exists('function_name')) :`. Then you can simply add the empty function to your child and cross selling is enabled.

Hope that clears it up

Basti
