### ISSUE TITLE
Google Meta doens't show up + wrong favicon

### ISSUE THREAD

**Issue by lennertfabriek** [bootscore/bootscore#57]
Hi Basti!

First time at github but I have a question about the google meta. I use the plugin Yoast and this always works. But now with searching for villamila google displays only the url (not any meta/snippet). And also the wrong favicon. I changed the favicon pictures in the child theme and also with the customizer. On the website it displays it good. But in the search engine (google) it displays the bootscore favicon. 

www.villamila.nl

**Comment by crftwrk** [comment]
Hi Lennert,

think this are two different things.

### Favicons

In order to display the favicons correctly it is important to do all of them. There are some missing on your site.

#### header.php

```php
<!-- Favicons -->
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo get_stylesheet_directory_uri(); ?>/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo get_stylesheet_directory_uri(); ?>/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo get_stylesheet_directory_uri(); ?>/img/favicon/favicon-16x16.png">
<link rel="manifest" href="<?php echo get_stylesheet_directory_uri(); ?>/img/favicon/site.webmanifest">
<link rel="mask-icon" href="<?php echo get_stylesheet_directory_uri(); ?>/img/favicon/safari-pinned-tab.svg" color="#0d6efd">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">
```
Change color for safari-pinned-tab, theme-color ans msapplication here.

Use the https://realfavicongenerator.net to generate favicons and copy them to your child `img/favicon`. There should be 10 files. Open `site.webmanifest` and remove `/` from `src` in lines 6 and 11 for Android touch icons (think Google uses this for search results). There should be no error in the console.

### Yoast and meta

I use this plugin as well without any problems and this has nothing to do with the theme. Are your settings in SEO > Search Appearance setup correctly and did you upload a logo there? Maybe try to reinstall Yoast and setup again?

**Comment by lennertfabriek** [comment]
Hi Basi, 

Thanks! I add all the files and the code of you. I deleted it before because I thought that's the reason it shows the bootscore favicon. 

So hope for the best now. 

Also I deleted the whole Yoast package and installed it again. Hopefully this will work.. But never had this before. Normaly google will show a standard meta if yoast is not working..

**Comment by crftwrk** [comment]
See, all favicons are there now. Give Google some time to crawl that. 

About the meta, this is very strange, because Google shows absolutely nothing. Did you tried to disable Yoast and using default site title in Settings > General? Just for testing.

**Comment by lennertfabriek** [comment]
Great.

First I deleted and installed again. I will try tomorrow your idea.

**Comment by lennertfabriek** [comment]
Hi Basti, 

The favicon is still the bootscore one.. do you know another solution?

**Comment by crftwrk** [comment]
To be honest, no idea. Because Google doesn't show a [meta description](https://www.google.com/search?q=villamila.nl&sxsrf=AOaemvJBP4lTyFw86QMZOlS5AjJQgXfEng%3A1639995179753&source=hp&ei=K1fAYZy0KreQxc8PvIqM-A8&iflsig=ALs-wAMAAAAAYcBlO9Oa2xe9_zP_MPbeMgy5ZEl1FWso&ved=0ahUKEwjc9fmQkvL0AhU3SPEDHTwFA_8Q4dUDCAk&uact=5&oq=villamila.nl&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBAgjECcyCggAEAgQDRAKEB46BwgjEOoCECc6BggjECcQEzoLCC4QgAQQxwEQrwE6BQgAEIAEOg4ILhCABBCxAxDHARCjAjoOCC4QgAQQsQMQxwEQ0QM6CAguELEDEIMBOggIABCABBCxAzoECAAQQzoLCAAQgAQQsQMQgwE6CAgAELEDEIMBOgsILhCABBDHARDRAzoRCC4QgAQQsQMQgwEQxwEQowI6CAguEIAEELEDOgUILhCxAzoFCC4QgAQ6BwgAEIAEEAo6DQguEIAEEMcBEK8BEAo6BQguEMsBOgUIABDLAToKCC4QxwEQrwEQDToECAAQDToGCAAQDRAeUOoGWJ0jYMUnaAFwAHgAgAGkAYgBzQqSAQM1LjeYAQCgAQGwAQo&sclient=gws-wiz) either, I think that's more due to your WordPress or Yoast. I would create a reduced test case to investigate further:

- Install a fresh WordPress on a new domain.
- Install WooCommerce
- Install Yoast
- Download bootScore (5.0.2.2) and your child via ftp from https://villamila.nl and install them on the new site.
- Check how Google will show new site search results.
- If the bug is still there, switch to a default WP theme.
- If the bug is still there, disable Yoast and use default WP Tagline in Settings > General.
- If all not help https://wordpress.org/support/plugin/wordpress-seo/

**Comment by justinkruit** [comment]
Hi @lennertfabriek, fellow Dutchman here. Just checked your site, and did some checks. So far I didn't see any problems. What I did spot is that www. and without www. doesn't load the same site, I recommend fixing that.

I assume this bug doesn't come from bootScore, as the doesn't have any detailed SEO.

I could potentially help with searching for the problem, but I would need access to some resources, and it's not really suitable for the GitHub issue. If you still need some help, we could set up a chat somewhere.

**Comment by lennertfabriek** [comment]
@justinkruit Hi, thanks for your help. I will check in my hosting account if there is a problem. Otherwise I will sent you my mobile number via email if you want (email from your bio). 

@crftwrk And also I will try this if we can't find anything.

**Comment by crftwrk** [comment]
It seems that this has been fixed. [Google](https://www.google.com/search?q=villamila.nl&sxsrf=AOaemvI2kYFgGchRlKnoWDH_zjJy2TryZQ%3A1640280387791&ei=Q7HEYfKuL7CGxc8PlpC0-A8&ved=0ahUKEwiy3OHOuPr0AhUwQ_EDHRYIDf8Q4dUDCA4&uact=5&oq=villamila.nl&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBAgjECcyCggAEAgQDRAKEB46BggjECcQEzoLCC4QgAQQxwEQrwE6BQgAEIAEOg4ILhCABBCxAxDHARCjAjoOCC4QgAQQsQMQxwEQ0QM6CAgAEIAEELEDOgQILhBDOgsIABCABBCxAxCDAToECAAQQzoICAAQsQMQgwE6BQguEIAEOgsILhCABBDHARDRAzoRCC4QgAQQsQMQgwEQxwEQowI6CAguEIAEELEDOgUILhCxAzoFCAAQsQM6BwgAEIAEEAo6DQguEIAEEMcBEK8BEAo6BQguEMsBOgUIABDLAToKCC4QxwEQrwEQDToECAAQDToGCAAQDRAeSgQIQRgASgQIRhgAUABY1BZguxtoAHAAeACAAb0BiAHcCpIBAzUuN5gBAKABAcABAQ&sclient=gws-wiz)
