### ISSUE TITLE
Problem with adding logo

### ISSUE THREAD

**Issue by tanukiux** [bootscore/bootscore#58]
Hey! I just started using bootscore a while ago.

I have weird problem, because my logo in svg does not want to appear on the screen, I have tried multiple ways, but it i can't make it work.
my header.php code:
<header id="masthead" class="site-header">

		
		
      <div class="text-uppercase">

        <nav id="nav-main" class="navbar navbar-expand-lg navbar-dark" style="background:transparent;">

          <div class="container">

            
            <a class="navbar-brand" href="<?php echo esc_url(home_url()); ?>"><img src="<?php echo esc_url(get_stylesheet_directory_uri()); ?>/img/logo/askay-logo.svg" alt="logo"></a>
         
        
 <span class="navbar-text text-light ml-4">
        .est 2021
      </span>
          
![image](https://user-images.githubusercontent.com/85894824/146173252-93d384f1-8315-44f3-9d64-2f6747ede623.png)

**Comment by crftwrk** [comment]
Hi,

a link to your site would be very helpful to check.

**Comment by tanukiux** [comment]
Sure :) http://www.askay.eu/strona/

**Comment by crftwrk** [comment]
Path in your header.php is still `http://www.askay.eu/strona/wp-content/themes/bootscore-child-main/img/logo.svg` and your svg is not in viewport.

Check fixed logo here https://dev.bootscore.me/ and download by right click > save. 

Solved?

**Comment by tanukiux** [comment]
interesting, i will check the logo fix

**Comment by tanukiux** [comment]
I don't understand, but thanks :o

**Comment by crftwrk** [comment]
The path to your logo is still wrong.

Use this in header.php:

`<a class="navbar-brand" href="<?php echo esc_url(home_url()); ?>"><img src="<?php echo esc_url(get_stylesheet_directory_uri()); ?>/img/logo/logo.svg" alt="logo" class="logo md"></a>`, 

Grab your logo from here https://dev.bootscore.me and paste it to child `img/logo/logo.svg`. Start renaming first if this works fine.

The original logo has a height on 27px and no whitespace around. Your one was round 500px height and had 1000px whitespace. That's why this does not work. Recommend to edit logo in the original file instead creating a new one.

**Comment by crftwrk** [comment]
> i just couldn't figure out why its not displaying.

Your image had too much whitespace around. You just saw the whitespace ;-)
