### ISSUE TITLE
How to override my-account-offcanvas.php in Bootcommerce-Child 

### ISSUE THREAD

**Issue by Lo1176** [bootscore/bootscore#61]
Hi Basti,

How to override `my-account-offcanvas.php` with **Bootcommerce-Child**?

I tried to copy the file in bootcommerce-child/woocommerce/myaccount/my-account-offcanvas.php but nothing appends.

**Comment by crftwrk** [comment]
Hi Lo,

yes, this is an own file and not part of WooCommerce. That's why you can't override this in the same way like the other WC files.

1. Copy file like you did it to **bootcommerce-child/woocommerce/myaccount/my-account-offcanvas.php**

2. Open **header.php** and search for this:

```php
<?php include get_template_directory() . '/woocommerce/myaccount/my-account-offcanvas.php'; ?>
```

3. Replace `get_template_directory()` with `get_stylesheet_directory()`

```php
<?php include get_stylesheet_directory() . '/woocommerce/myaccount/my-account-offcanvas.php'; ?>
```

4. Edit file as you want.

**Comment by Lo1176** [comment]
Thanks Basti!
I will do this.
I'm trying to understand how Wordpress works :
is `get_template_directory()` for the main theme and `get_stylesheet_directory()` for the child theme?

**Comment by crftwrk** [comment]
> is `get_template_directory()` for the main theme and `get_stylesheet_directory()` for the child theme?

Exactly. `get_stylesheet_directory()` is for the active theme where the style.css is located while `get_template_directory()` always links to the main-theme.

**Comment by Lo1176** [comment]
Thanks a lot for your clear answers!
Merry Christmas 🎄
