### ISSUE TITLE
Off-canvas nav pushed off to side on mobile

### ISSUE THREAD

**Issue by artinflight** [bootscore/bootscore#63]
Bootscore is an excellent framework! Thank you for this.

Developing a simple site for a client using Bootscore. Issue I'm having is the off-canvas nav is pushed off to the side of the page on mobile.

https://SmileyLogistics.ca

Your help is greatly appreciated!

**Comment by justinkruit** [comment]
I'm not able to actually confirm (currently not on PC), but the navbar button is only being pushed off the screen because something else made the page bigger.

It seems like it's because the animation you use, but on a container you don't have overflow-x: hidden, so the animations fading from the right make the page wider. You can test this by scrolling to the last div that has the fade animation from the right (Same Day Transportation), and then scrolling up to hide the go-to-top button. It will have the correct width again.

**Comment by artinflight** [comment]
@justinkruit Applying a global overflow-x: hidden to my containers worked to fix the issue!

Thank you kindly!!
