### ISSUE TITLE
[Feature Request] Quantity Swatches for sidebar cart (no reload)

### ISSUE THREAD

**Issue by username0136** [bootscore/bootscore#631]
### Describe the feature that you'd like

I'm requesting the addition of quantity swatches for the sidebar cart. [Here's a visual representation](https://github.com/bootscore/bootscore/assets/102938585/c3be87ea-03f6-45f4-ab4d-46ccaa1048d9), and they should operate seamlessly with Ajax.

![image](https://github.com/bootscore/bootscore/assets/102938585/c3be87ea-03f6-45f4-ab4d-46ccaa1048d9)

For implementation reference, check out the same feature in the [selleradise-lite theme repository](https://github.com/redoxbird/selleradise-lite/). This functionality is already integrated into that theme.

### Why is this feature needed? What problem does it solve?

This enhancement significantly improves the customer experience.
Currently, it's cumbersome for customers to navigate to the cart page, modify quantities, and then click the update cart button. With quantity swatches in the sidebar cart, this process becomes more **straightforward**.

I usually hide the "view cart" button to streamline the shopping experience, encouraging users to utilize the sidebar cart. This not only simplifies their journey but also allows for a quicker checkout.

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
Totally agree that this will be a nice feature. However, this seems to be a tough job and the question is: Are you able to contribute and work on this?

Quickly checked the selleradise theme and it seems that it does not use the `mini-cart.php` for the sidebar cart. It has to deeply figured out how the cart works there.

Another option is to modify the mini-cart with quantity https://gist.github.com/ashokmhrj/fda5a23f7bdfc55749bd2bd53c64a8ca.

Third option is trying to hard code the new mini cart block in the theme https://developer.woo.com/2023/06/16/best-practices-for-the-use-of-the-cart-fragments-api/. This block has already the qty feature. Since Woo started to replace the classic templates with blocks, this seems to be the most future proved option.

Let me know what you think.
