### ISSUE TITLE
[BUG] Woocommerce Products Shortcode

### ISSUE THREAD

**Issue by andreiflorentin** [bootscore/bootscore#661]
### Describe the bug

Hello,
When I use shortcodes to display products not works pagination. For example with this [products columns="4" on_sale="true" per_page="28" paginate="true" ] not display pagination. Do you can help me, please?

**Comment by crftwrk** [comment]
Hi,

thank you for pointing this out, there is a linked PR https://github.com/bootscore/bootscore/pull/663 which fixes that.

Until this PR is merged, go to your main-theme's folder `woocommerce/loop/pagination.php`and replace the entire content with tis one https://github.com/bootscore/bootscore/blob/Fix-WC-pagination/woocommerce/loop/pagination.php.

BTW, `columns="4"` has no effect because columns are overridden by the theme. Using `[products on_sale="true" per_page="28" paginate="true"]` is enough.

**Comment by andreiflorentin** [comment]
It's ok now. Thank you!

**Comment by crftwrk** [comment]
You‘re welcome. I reopen this issue because there is a linked PR which closes this when merged.
