### ISSUE TITLE
Accessibility issues - WAVE

### ISSUE THREAD

**Issue by mandrasch** [bootscore/bootscore#72]
Hi,

first of all thanks very much for providing this! I was really happy when I discovered your starter theme! 🙏   

I ran quick check with https://wave.webaim.org/, there seem to be some accessibility issues, e.g. in the navigation. I checked the sub page https://bootscore.me/theme/page-sidebar-left/ just quickly.

![image](https://user-images.githubusercontent.com/777278/149815696-c0d43ebe-30a1-4c2f-8b63-18caecbd52fc.png)

Other good a11y test tools:
- [Axe ](https://www.deque.com/axe/browser-extensions/)
- https://accessibilityinsights.io/en/downloads/

Just wanted to let you know.

Looking forward to use bootscore for some projects! Happy to help as well with accessibility issues (to the best of my knowledge/abilities ;-))

Cheers,
Matthias

**Comment by crftwrk** [comment]
Hi Matthias,

thank you for figuring this out. Buttons contains only an icon and it seems that this is not enough. This can be fixed by adding a `visually-hidden-focusable` text to buttons in header.php.

```html
<!-- Search Toggler -->
<button class="btn btn-outline-secondary ms-1 ms-md-2 top-nav-search-md" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-search" aria-expanded="false" aria-controls="collapse-search">
  <i class="fas fa-search"></i><span class="visually-hidden-focusable">Search</span>
</button>
```

We would be happy if you want to contribute and create a pull request for this.

For the "very low contrast" that the tool complains about, I think it's better to trust the human eye than machines. I don't see any low contrast between the `primary` color links and the `bg-light` background for example in the footer.
