### ISSUE TITLE
Header widget

### ISSUE THREAD

**Issue by Schiehsl3** [bootscore/bootscore#74]
Hello I am new to using the theme and I am trying to replicate a feature the main bootscore site has. 

I understand how the  "Top Nav" Section works but when you are in mobile view and open up the menu you can see the two buttons on that extended nav bar. How do I do that? Is that something custom coded in and if so it should really be mentioned because its a very useful feature I'd like added to my site. 

![image](https://user-images.githubusercontent.com/1226464/150663759-bba291d9-9a24-4ad2-834c-b7bf49a8bafe.png)

**Comment by crftwrk** [comment]
Hi,

this is roughly hard-coded in top-nav widget position and header.php. Because there is not enough space in navbar to show buttons in mobile view, they moved to offcanvas while dark-mode switch is always in top-nav widget using [display utilities](https://getbootstrap.com/docs/5.1/utilities/display/).

### Top-nav widget

Use a custom HTML widget in top-nav widget position: 

```html
<div class="d-flex">
  <div class="d-flex align-items-center ms-md-n2 me-2 me-lg-3">
    [bs-dark-mode]
  </div>
  <a href="https://bootscore.me/#download" class="btn btn-outline-primary d-none d-lg-block">Download</a>
  <a class="btn btn-dark btn-github ms-2 d-none d-lg-block" href="https://github.com/bootscore" target="_blank" title="bootScore @ GitHub" rel="noopener"><i class="fab fa-github"></i><span class="d-none"> GitHub</span></a>
</div>
```

### header.php

You can show everything what you want in offcanvas, but hide it above the breakpoints using `d-*-none` class. Paste following HTML to your header.php in offcanvas direct after `<!-- Bootstrap 5 Nav Walker Main Menu End -->`.

```html
<!-- Bootstrap 5 Nav Walker Main Menu End -->
<div class="d-lg-none mt-3 pt-4 pb-4 border-top">
  <div class="row">
    <div class="col-6">
      <a href="https://bootscore.me/#download" class="btn btn-outline-primary w-100 btn-download">Download</a>
    </div>
    <div class="col-6">
      <a class="btn btn-dark w-100" href="https://github.com/bootscore" target="_blank" title="bootScore @ GitHub" rel="noopener"><i class="fab fa-github"></i> GitHub</a>
    </div>
  </div>
</div>
```

Does this help?

**Comment by Schiehsl3** [comment]
It does and it doesn't. It solved the question but I just wonder... why? Seems a little silly to have to custom coding it in. How come you never put it as a new widget type like Offset bottom widget? I am sure a lot of people would find use out of it to be there by default. Seems like something overlooked a bit

**Comment by crftwrk** [comment]
bootScore is a starter theme for developers. You must code and edit it by yourself. We are here to help you and solve issues. 

In my opinion, adding a widget in the offcanvas menu by default doesn't make sense. Some use the collapse menu instead offcanvas. It is also related to the breakpoints where the widget is shown and where not. In short, this is something what you should do in your child. You can simply register as many widgets as you want and show them where you want.
