### ISSUE TITLE
[BUG] WooCommerce Legacy REST API

### ISSUE THREAD

**Issue by Remzi1993** [bootscore/bootscore#777]
### Describe the bug

This WP theme uses the WooCommerce Legacy REST API and this will be removed in WooCommerce 9.0
Please upgrade WooCommerce.

**Comment by crftwrk** [comment]
Theme has nothing to do with REST API, it's somewhere in your plugin area which uses this. Since WC 8.8, WooCommerce checks if REST API is still used and installs the WooCommerce Legacy REST API plugin by itself because as you mentioned, REST API will be removed in v9. 

You can check which plugins uses the API in Backend > WooCommerce > Settings > Advanced > REST API.
