### ISSUE TITLE
Bootstrap Block buttons

### ISSUE THREAD

**Issue by samtruss1986** [bootscore/bootscore#83]
Hi All, firstly thanks in advance.

My Issue is with the pre defined bootstrap buttons within bootstrap blocks. Currently I can only select between Primary and Secondary (See Photo)

![Screenshot 2022-01-31 at 16 02 10](https://user-images.githubusercontent.com/9266232/151830320-cb97f5ee-c854-48a5-8df2-8c36bfd0f90e.png)

Which shows the two buttons below

![Screenshot 2022-01-31 at 16 02 01](https://user-images.githubusercontent.com/9266232/151830315-2a687a1b-a84f-4931-8f9a-724082055d70.png)

I've tried adding bootstrap classes btn-outline-* to the advanced CSS  however this doesn't change the button as WP or the theme is adding they btn-primary after. 

What I would like is the option below for the button to be a outline (see below) however I can't for the life of me find any docs on how to do this.
![Screenshot 2022-01-31 at 16 01 55](https://user-images.githubusercontent.com/9266232/151830318-c23565d0-d370-4a22-83b8-53db2dacd201.png)

Thanks, and apologies for being a noob and if this has been posted before. 

Sam.

**Comment by crftwrk** [comment]
Hi,

bootScore does't support Bootstrap to Gutenberg, that would go beyond the scope of the project. Gutenberg's primary has nothing to do with Bootstrap's primary, this are two different things. 

If you want to use Bootstrap in Gutenberg, luckily there are plugins for this (not tested):

- https://wordpress.org/plugins/wp-bootstrap-blocks/
- https://wordpress.org/plugins/wp-editor-bootstrap-blocks/

But we recommend to use Gutenberg HTML block instead of plugins:

```html
<a href="#" class="btn btn-outline-primary">Button</a>
```

This is the cleanest way and gives you the full control. Most bootScore sites are build that way.

You can use HTML block to build your content as well:

```html
<!-- Gutenberg HTML block -->
<div class="row">
    <div class="col-md-6">
        content
    </div>
    <div class="col-md-6">
        content
    </div>
</div>
```


If you want to use a block inside the columns do it like this:

```html
<!-- Gutenberg HTML block -->
<!-- open row and cols -->
<div class="row">
    <div class="col-md-6">
```
`Gutenberg heading block`

```html
<!-- Gutenberg HTML block -->
    </div>
    <!-- close col -->
    <!-- open col -->
    <div class="col-md-6">
```

`Gutenberg gallery block`

```html
<!-- Gutenberg HTML block -->
    </div>
</div>
<!-- close row and col -->
```

BTW, we plan to add some basic color support to Gutenberg in future https://github.com/bootscore/bootscore/issues/55.

Does this help?
